### ISSUE TITLE
[BUG] Incompatibility between Settings Extender and libWrapper in V9

### ISSUE THREAD

**Issue by RogueEntityX** [ruipin/fvtt-lib-wrapper#59] opened 2021-12-14 01:24 UTC
I read the posting info, and realize this is likely to be a Settings extender issue, but I'm ignorant in programming or the meaning of the error messages, so I'm cross-posting this on the Settings Extender git as well (https://gitlab.com/foundry-azzurite/settings-extender/-/issues/6)

Both Settings Extender 1.1.6+0.8.6 and libWrapper 1.11.0.1 are individually marked as compatible with V9, and when enabled individually, both seem to operate with no issue.

However, when both are enabled (even in a clean world with no other modules) Foundry's Configure Settings window will not open, and the following error is logged in the console when you try:

![image](https://user-images.githubusercontent.com/72455534/145914993-90428c96-fb2c-4bf3-aa7c-eadfa4361c6b.png)

Disabling either module removes both the issue and the error.

![image](https://user-images.githubusercontent.com/72455534/145915220-c0d6e4d4-ff24-429f-8a6d-b32484cf0a31.png)

**Comment by ruipin** [comment] 2021-12-14 01:30
Settings extender `1.1.6+0.8.6` seems to be out-of-date, with the newest version being `1.1.7+9`.

I can't reproduce this with the updated version (`1.1.7+9`) and libWrapper `1.11.0.1`.

**Comment by RogueEntityX** [comment] 2021-12-14 01:43
Hrm....I reported the version that I have installed after updating, and 1.1.6+0.8.6 seems the be the furthest it will update within Foundry. It does _appear_ to me to be V9-compatible, based on the lack of compatibility warning tags in both the Add-on Modules tab in setup: 
![image](https://user-images.githubusercontent.com/72455534/145916816-da4a1a0b-18a4-445e-8884-7c734ef6bb84.png)

and the Manage Modules window in a world: 
![image](https://user-images.githubusercontent.com/72455534/145916934-f8ee56f6-7000-406c-9053-10822b5179a5.png)

**Comment by RogueEntityX** [comment] 2021-12-14 01:45
Interestingly enough, I just checked the module.json in the Setting Extender module folder in data/modules on my disk, and it does show as 1.1.7+9, but still shows up at 1.1.6+0.8.6 in Foundry.

![image](https://user-images.githubusercontent.com/72455534/145917633-935b9849-180d-4bdc-866d-b30f6462ff48.png)

so I'll go bark up Azzurite's tree a bit more.

**Comment by ruipin** [comment] 2021-12-14 01:47
I grabbed `1.1.7+9` just fine using the UI, and looking at the changes between 1.1.6+0.8.6 and 1.1.7+9, it is clearly the change that adds v9 compatibility to the manifest, and seems to address this exact error you were seeing.

I suggest restarting the Foundry server, something might've gone wrong and it is using the pre-update version for some reason. Restarting it should force the server to reload from disk. Can also try to unninstall + reinstall the module as well.

Anyway, at this point I am essentially convinced this is not a libWrapper issue, so will close this report. Feel free to re-open if it turns out I am wrong.

**Closed by ruipin** 2021-12-14 01:47 UTC
Labels: bug
