### ISSUE TITLE
weaponProf variable unassaigned?

### ISSUE THREAD

**Issue by BradyIrvine** [ruipin/fvtt-lib-wrapper#75] opened 2023-01-11 23:30 UTC
I apologize if this should be in the DAE page and not libWrapper, just noticed it originated from the libWrapper Init.

![libWrapperDAEconflict](https://user-images.githubusercontent.com/12041431/211940245-bf46172b-07a6-44ae-8a37-649b584bf620.JPG)

**Comment by ruipin** [comment] 2023-01-12 18:17
Thanks for the report, but there is nothing I can help you with and libWrapper is almost certainly working fine. 

Most libWrapper errors are not caused by libWrapper itself, but instead by a module that uses it. In this case, this issue is almost certainly caused by DAE, and you should report it to them. It occurs during libWrapperInit because this runs around the FVTT initialisation phase.

Usually, you should report bugs to the module developers themselves (in this case DAE), and then the module developer will report an issue to me if they debug it to be caused by libWrapper (which is quite rare, as libWrapper is a stable library used by hundreds of modules).

Closing as invalid.

**Closed by ruipin** 2023-01-12 18:17 UTC
Labels: invalid
