### ISSUE TITLE
v1.4.0.0 has caused serious breakages to many modules.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [ruipin/fvtt-lib-wrapper#30] opened 2021-04-11 07:22 UTC
i have alot of modules such as custom hotbar/midi qol/ automated animations etc etc that require this module as a dependancy its also happening with multi level tokens. where im having a constant flashing token with an error due to the libwrapper. please fix this asap. i need these running for my games.

**Comment by apoapostolov** [comment] 2021-04-11 08:09
I have downgraded to 1.3.6 as well. My world (zip below) freezes when attempting to load with libwrapped 1.4
https://we.tl/t-IPZSJSOFih

**Comment by KammaKhazi** [comment] 2021-04-11 09:32
Similar issues here since the 1.4.0 update my world wouldn't load and just hung at 'pause' when loading. Rolling back to v1.3.6 fixed the issue.

**Comment by ruipin** [comment] 2021-04-11 13:03
Thanks for the reports. I'm looking into these right now.

It seems at least some of these modules aren't on the [Modules using libWrapper](https://github.com/ruipin/fvtt-lib-wrapper/wiki/Modules-using-libWrapper) list, so I didn't test them before releasing.

I've changed v1.4.0.0 to be marked as "Pre-release", which means nobody will update to it automatically any more.

**Comment by ruipin** [comment] 2021-04-11 13:46
[v1.4.1.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.4.1.0) should fix all these issues. In particular, Norc's custom hotbar now works.

In short, Foundry's `Hooks.once` behaviour was half-broken by the the previous version.
If you encounter any more issues, please let me know.

**Comment by ruipin** [comment] 2021-04-11 14:32
Re-opening as some people on Discord are still reporting issues.

**Comment by ruipin** [comment] 2021-04-11 17:46
It seems these issues were not actually caused by libWrapper. I'll leave this issue open for a while in case anyone reports something else, but for now, as long as you are on [v1.4.1.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.4.1.0) or above, everything should be working fine.

**Comment by ruipin** [comment] 2021-04-12 20:22
No further breakage has been reported, closing.

**Closed by ruipin** 2021-04-12 20:22 UTC
Labels: bug, high-priority
