### ISSUE TITLE
[CORE ISSUE] libWrapper fails on v10p1 / v10p2 when modules try to register a wrapper

### ISSUE THREAD

**Issue by tposney** [ruipin/fvtt-lib-wrapper#66] opened 2022-05-01 06:46 UTC
I am starting to look at compatibility of my modules with v10.
However libWrapper.register fails with 
```
This is *not* a libWrapper bug.

== Technical Details:
Detected by libWrapper.
Package ID= unknown:socketlib
Error= Package 'socketlib' is not a valid package.

[Detected 1 package: socketlib]
    at de (libWrapper-api.js:290:10)
    at Function.🎁register [as register] (libWrapper-api.js:470:24)
    at Object.fn (socketlib.js:21:13)
    at Function.#call (foundry.js:354:20)
    at Function.callAll (foundry.js:311:17)
    at Game.initialize (foundry.js:6409:11)
    at Wrapper.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:511:22)
    at Game.🎁libWrapperInit (libWrapper-api.js:793:11)
```
And does this for all modules.
**Describe the question**
So my question: "Is libwrapper compatible with v10 p2?" I could not find any mention of an issue, but wanted to make sure it's not something in my setup causing the problem.

**Comment by ruipin** [comment] 2022-05-01 16:30
Thanks for the bug report. I can reproduce this, It seems indeed that libWrapper is broken in V10p2. Not certain, but it seems Core has changed the way it stores modules. I'm investigating this.

**Comment by ruipin** [comment] 2022-05-01 16:43
It seems this happens because `Module#active` is broken in v10p2: https://gitlab.com/foundrynet/foundryvtt/-/issues/7023

According to the gitlab issue above, this will be fixed in v10p3.

Will keep this ticket open until the fix is confirmed.

**Comment by ruipin** [comment] 2022-05-13 10:50
This appears to now be resolved in v10p3, closing.

**Closed by ruipin** 2022-05-13 10:50 UTC
Labels: core-issue
