### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by foxreinhold** [ruipin/fvtt-lib-wrapper#63] opened 2022-01-30 03:27 UTC
⚠ Most errors triggered by libWrapper are not caused by libWrapper itself, but by a module/package. Do not open a support ticket using this form unless you are seeing an **internal** libWrapper error or are a **package developer** who needs support. We also do not provide support for packages that promote or otherwise endorse piracy. Your issue will be closed as invalid if you do not fulfill these requirements.

The easiest way to find support is to ask the community. The largest community-provided support channels are:
- [FoundryVTT Discord](https://discord.gg/foundryvtt)'s #modules-troubleshooting channel
- [FoundryVTT Reddit](https://www.reddit.com/r/FoundryVTT)

--------------------

**Confirm you have read the above**

**Describe the bug**
Libwrapper 1.12.0.0 completely fails to hook on Firefox 96.0.3 GM login.  Self hosted on ubuntu using NodeJS current LTS.  This was not present in 1.1.4.0

**To Reproduce**
1. Have Libwrapper and a module that depends on libwrapper active (Wall Height was used for testing).
2. Login to GM account using Firefox.
3. Module that has libwrapper dependency will not be able to detect libwrapper 1.12.0.0.  Reverting to Libwrapper 1.11.4.0 fixes issues and libwrapper registers successfully.
4. Additionally, the map will not render, claiming WebGL context has been lost.  This does not happen on Chrome.

**Expected behavior**
Libwrapper 1.12.0.0 does not exhibit this behavior on Chrome.

**Technical Details (please complete the following information):**
 - LibWrapper Version 1.12.0.0
 - FoundryVTT Version 9.245
 - Firefox 96.0.3 Windows 10, hosted on Ubuntu 21.10 Node JS

**Additional context**

Console warnings do appear:

![image](https://user-images.githubusercontent.com/77173822/151685529-852b6647-88c7-4873-a429-a752ef4cf75b.png)

**Comment by ruipin** [comment] 2022-01-30 03:33
I cannot reproduce this with the versions of the software you indicated.

Which module has the problem?

**Comment by ruipin** [comment] 2022-01-30 05:22
After discussion on Discord, it seems this was caused by malformed log verbosity settings. The code did not correctly handle the case where the log verbosity setting was stored as a string, rather than as an integer.

Should be fixed in [v1.12.1.0](https://github.com/ruipin/fvtt-lib-wrapper/releases/tag/v1.12.1.0)

**Closed by ruipin** 2022-01-30 05:22 UTC
Labels: bug
