### ISSUE TITLE
Any plans to make this work with 0.8.7?

### ISSUE THREAD

**Issue by wwitunsky** [ruipin/fvtt-lib-wrapper#41] opened 2021-06-17 02:05 UTC
Currently this crashes 0.8.7 and stops many other modules from functioning including DAE that are dependent on this module.

**Comment by ruipin** [comment] 2021-06-17 02:13
You'll need to provide more information about what you mean by "this crashes 0.8.7".

It works perfectly fine for me with all modules in [this list](https://github.com/ruipin/fvtt-lib-wrapper/wiki/Modules-using-libWrapper) installed and enabled (except where they are not compatible with 0.8.x). I just hadn't updated the compatibility version to 0.8.7 yet.

**Comment by wwitunsky** [comment] 2021-06-17 02:27
Ill do some more poking around to give you the error. Not a wiz with this stuff so please bare with me.

**Comment by ruipin** [comment] 2021-06-17 02:30
Assuming you have libWrapper installed and enabled, it should give you an error message. Which one is it?

You should be able to open the browser console (press F12), refresh Foundry, and search for the corresponding red message there. This message should be expandable, and it will give you a full stack trace of the error. Can you post this?

**Comment by wwitunsky** [comment] 2021-06-17 03:09
Sure doing a campaign at the moment but will post as soon as I can.

**Comment by wwitunsky** [comment] 2021-06-17 04:11
This is one of the libwrapper dependencies.



<div tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">VM8778:8</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;"><span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;">I: Error detected in module 'macro-icons'.
libWrapper: Can't wrap 'TextEditor._createEntityLink', target does not exist or could not be found.
    at new 🎁constructor (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:11298</span>)
    at Y (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:26770</span>)
    at <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:29623</span>
    at Function.🎁register [as register] (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:29626</span>)
    at <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/modules/macro-icons/main.js:7:14</span>
    at Function._call (eval at &lt;anonymous&gt; (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/modules/lib-wrapper/lib-wrapper.js:1:33401</span>), &lt;anonymous&gt;:4:14)
    at Function.callAll (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/scripts/foundry.js:153:12</span>)
    at Game.setupGame (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/scripts/foundry.js:4307:11</span>)
    at async Game._initializeGameView (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/scripts/foundry.js:5117:5</span>)
    at async Game.initialize (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">http://localhost:30000/scripts/foundry.js:4202:5</span>)</span></span></span></div><div class="" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">
&nbsp; | _call | @ | VM8778:8
-- | -- | -- | --
&nbsp; | callAll | @ | foundry.js:153
&nbsp; | setupGame | @ | foundry.js:4307
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | setupGame | @ | foundry.js:4284
&nbsp; | _initializeGameView | @ | foundry.js:5117
&nbsp; | _initializeView | @ | foundry.js:5093
&nbsp; | initialize | @ | foundry.js:4202
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | initialize | @ | foundry.js:4196
&nbsp; | 🎁call_wrapped | @ | libWrapper-wrapper.js:466
&nbsp; | 🎁libWrapperInit | @ | libWrapper-api.js:599
&nbsp; | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:160
&nbsp; | window.addEventListener.once | @ | foundry.js:53073
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | window.addEventListener.once | @ | foundry.js:53072

</span></div>

**Comment by wwitunsky** [comment] 2021-06-17 04:14
<div tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; flex: 0 0 auto; color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">VM26250:8</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;"><span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read property 'addChild' of null
    at TokenLayer.createObject (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:19472</span>)
    at TokenDocument5e.get object [as object] (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:8369</span>)
    at TokenLayer.get (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:19529</span>)
    at Function._onRenderChatMessage (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">concentrator.js:48</span>)
    at <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">signal.js:192</span>
    at Function._call (eval at &lt;anonymous&gt; (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">libWrapper-error_listeners.js:56</span>), &lt;anonymous&gt;:4:14)
    at Function.call (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:179</span>)
    at ChatMessage.getHTML (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:12950</span>)
    at async ChatLog._renderBatch (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:32162</span>)
    at async ChatLog._renderInner (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:32132</span>)</span></span></span></span></div><div class="" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 0, 0); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">
&nbsp; | _call | @ | VM26250:8
-- | -- | -- | --
&nbsp; | call | @ | foundry.js:179
&nbsp; | getHTML | @ | foundry.js:12950
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | getHTML | @ | foundry.js:12938
&nbsp; | _renderBatch | @ | foundry.js:32162
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | _renderBatch | @ | foundry.js:32162
&nbsp; | _renderInner | @ | foundry.js:32132
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | _renderInner | @ | foundry.js:32131
&nbsp; | _render | @ | foundry.js:2048
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | _render | @ | foundry.js:2042
&nbsp; | 🎁call_wrapped | @ | libWrapper-wrapper.js:466
&nbsp; | 🎁Application.prototype._render#lib-wrapper | @ | libWrapper-error_listeners.js:75
&nbsp; | 🎁Application.prototype._render#0 | @ | libWrapper-wrapper.js:160
&nbsp; | _render | @ | foundry.js:23186
&nbsp; | _render | @ | foundry.js:32123
&nbsp; | _render | @ | foundry.js:22995
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | _render | @ | foundry.js:22987
&nbsp; | render | @ | foundry.js:2004
&nbsp; | initializeUI | @ | foundry.js:4391
&nbsp; | setupGame | @ | foundry.js:4293
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | setupGame | @ | foundry.js:4284
&nbsp; | _initializeGameView | @ | foundry.js:5117
&nbsp; | _initializeView | @ | foundry.js:5093
&nbsp; | initialize | @ | foundry.js:4202
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | initialize | @ | foundry.js:4196
&nbsp; | 🎁call_wrapped | @ | libWrapper-wrapper.js:466
&nbsp; | 🎁libWrapperInit | @ | libWrapper-api.js:599
&nbsp; | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:160
&nbsp; | window.addEventListener.once | @ | foundry.js:53073
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | window.addEventListener.once | @ | foundry.js:53072

</span></div>

**Comment by wwitunsky** [comment] 2021-06-17 04:15
<div tabindex="-1" class="console-message-wrapper console-from-api console-error-level console-selected" role="treeitem" aria-expanded="true" style="box-sizing: border-box; min-width: 0px; min-height: 0px; outline-width: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: rgb(65, 115, 180); border-bottom: 1px solid rgb(65, 115, 180); background-color: rgb(41, 50, 61); --error-text-color: hsl(0deg 100% 75%); color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;"><span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">TypeError: Cannot read property 'addChild' of null
    at TokenLayer.createObject (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:19472</span>)
    at TokenDocument5e.get object [as object] (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:8369</span>)
    at TokenLayer.get (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:19529</span>)
    at Function._onRenderChatMessage (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">concentrator.js:48</span>)
    at <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">signal.js:192</span>
    at Function._call (eval at &lt;anonymous&gt; (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">libWrapper-error_listeners.js:56</span>), &lt;anonymous&gt;:4:14)
    at Function.call (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:179</span>)
    at ChatMessage.getHTML (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:12950</span>)
    at async ChatLog._renderBatch (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:32162</span>)
    at async ChatLog._renderInner (<span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(171, 171, 171); text-decoration: underline; cursor: pointer; word-break: break-all;">foundry.js:32132</span>)</span></span></span></span></div><div class="" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">
&nbsp; | _call | @ | VM26250:8
-- | -- | -- | --
&nbsp; | call | @ | foundry.js:179
&nbsp; | getHTML | @ | foundry.js:12950
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | getHTML | @ | foundry.js:12938
&nbsp; | _renderBatch | @ | foundry.js:32162
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | _renderBatch | @ | foundry.js:32162
&nbsp; | _renderInner | @ | foundry.js:32132
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | _renderInner | @ | foundry.js:32131
&nbsp; | _render | @ | foundry.js:2048
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | _render | @ | foundry.js:2042
&nbsp; | 🎁call_wrapped | @ | libWrapper-wrapper.js:466
&nbsp; | 🎁Application.prototype._render#lib-wrapper | @ | libWrapper-error_listeners.js:75
&nbsp; | 🎁Application.prototype._render#0 | @ | libWrapper-wrapper.js:160
&nbsp; | _render | @ | foundry.js:23186
&nbsp; | _render | @ | foundry.js:32123
&nbsp; | _render | @ | foundry.js:22995
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | _render | @ | foundry.js:22987
&nbsp; | render | @ | foundry.js:2004
&nbsp; | initializeUI | @ | foundry.js:4391
&nbsp; | setupGame | @ | foundry.js:4293
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | setupGame | @ | foundry.js:4284
&nbsp; | _initializeGameView | @ | foundry.js:5117
&nbsp; | _initializeView | @ | foundry.js:5093
&nbsp; | initialize | @ | foundry.js:4202
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | initialize | @ | foundry.js:4196
&nbsp; | 🎁call_wrapped | @ | libWrapper-wrapper.js:466
&nbsp; | 🎁libWrapperInit | @ | libWrapper-api.js:599
&nbsp; | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:160
&nbsp; | window.addEventListener.once | @ | foundry.js:53073
&nbsp; | async function (async) | &nbsp; | &nbsp;
&nbsp; | window.addEventListener.once | @ | foundry.js:53072

</span></div></div></div></div></div><div tabindex="-1" class="console-message-wrapper console-from-api console-warning-level" role="treeitem" aria-expanded="false" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: flex; border-top-width: ; border-top-style: ; border-top-color: transparent; border-bottom: 1px solid transparent; background-color: rgb(51, 43, 0); color: rgb(213, 213, 213); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="console-message" style="box-sizing: border-box; min-width: 0px; min-height: 17px; clear: right; position: relative; padding: 3px 22px 1px 0px; margin-left: 24px; flex: 1 1 auto; display: flex;"><span is="ui-icon" class="message-level-icon spritesheet-smallicons smallicon-warning" aria-label="Warning" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: inline-block; flex: 1 1 auto; position: absolute; left: -17px; top: 4px; user-select: none; background-position: var(--spritesheet-position); background-image: url(&quot;Images/smallIcons.svg&quot;); --spritesheet-position:-60px 10px; width: 10px; height: 10px;"></span><div class="console-message-stack-trace-toggle" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: row; align-items: flex-start;"><div class="console-message-stack-trace-wrapper" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 1 1 auto; display: flex; flex-direction: column; align-items: stretch;"><div tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto;"><span is="ui-icon" class="console-message-expand-icon spritesheet-smallicons smallicon-triangle-right icon-mask" style="box-sizing: border-box; min-width: 0px; min-height: 0px; display: inline-block; flex-shrink: 0; margin-bottom: -2px; background-color: rgb(145, 145, 145); -webkit-mask-position: var(--spritesheet-position); -webkit-mask-image: url(&quot;Images/smallIcons.svg&quot;); --spritesheet-position:0px 10px; width: 10px; height: 10px;"></span></div></div></div></div></div><br class="Apple-interchange-newline">

**Comment by ruipin** [comment] 2021-06-17 15:28
As the first error message helpfully states, it isn't a libWrapper issue but instead an issue with a module that probably hasn't been updated yet. In this case, at least `macro-icons` seems to be broken.

The other 2 errors are also not related to libWrapper, and seem to be caused by the module that has the file `concentrator.js`, which I presume is Combat Utility Belt.

Try disabling these two modules and see if you still get errors. I'll close this issue as invalid, and think about how to improve the error messages from libWrapper so that it is more obvious libWrapper isn't causing this type of issues.

**Closed** 2021-06-17 15:29 UTC
Labels: invalid

**Comment by wwitunsky** [comment] 2021-06-17 19:52
Much Appreciated
Still trying to understand these things thank your for the prompt assistance
