### ISSUE TITLE
Getting error when importing an item

### ISSUE THREAD

**Issue by Avitale34** [ruipin/fvtt-lib-wrapper#36] opened 2021-06-02 12:53 UTC
Receiving this error whenever I try to import an item. Screen shot for ease.
![image](https://user-images.githubusercontent.com/65961637/120483343-05795500-c380-11eb-9e29-a01e70aadbc8.png)

VM6936:7 Foundry VTT | Error thrown in hooked function 
_call @ VM6936:7
callAll @ foundry.js:153
callback @ foundry.js:8866
(anonymous) @ foundry.js:8805
_handleUpdateDocuments @ foundry.js:8805
_updateDocuments @ foundry.js:8693
async function (async)
_updateDocuments @ foundry.js:8684
update @ backend.mjs:154
async function (async)
update @ backend.mjs:151
updateDocuments @ document.mjs:365
🎁call_wrapped @ libWrapper-wrapper.js:448
updateDocuments @ ItemContainer.js:77
🎁call_wrapper @ libWrapper-wrapper.js:557
🎁CONFIG.Item.documentClass.updateDocuments#0 @ libWrapper-wrapper.js:144
update @ document.mjs:447
🎁call_wrapped @ libWrapper-wrapper.js:448
_update @ ItemContainer.js:150
🎁call_wrapper @ libWrapper-wrapper.js:557
🎁CONFIG.Item.documentClass.prototype.update#0 @ libWrapper-wrapper.js:144
importFromJSON @ foundry.js:9646
(anonymous) @ foundry.js:9671
Promise.then (async)
callback @ foundry.js:9671
submit @ foundry.js:20351
_onClickButton @ foundry.js:20314
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
VM6936:8 TypeError: Cannot read property 'id' of null
    at delayedSort (init.js:114)
    at init.js:150
    at Function._call (eval at <anonymous> (libWrapper-errors.js:249), <anonymous>:4:14)
    at Function.callAll (foundry.js:153)
    at ClientDatabaseBackend.callback (foundry.js:8866)
    at foundry.js:8805
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateDocuments (foundry.js:8805)
    at ClientDatabaseBackend._updateDocuments (foundry.js:8693)
    at async Function.updateDocuments (document.mjs:365)
_call @ VM6936:8
callAll @ foundry.js:153
callback @ foundry.js:8866
(anonymous) @ foundry.js:8805
_handleUpdateDocuments @ foundry.js:8805
_updateDocuments @ foundry.js:8693
async function (async)
_updateDocuments @ foundry.js:8684
update @ backend.mjs:154
async function (async)
update @ backend.mjs:151
updateDocuments @ document.mjs:365
🎁call_wrapped @ libWrapper-wrapper.js:448
updateDocuments @ ItemContainer.js:77
🎁call_wrapper @ libWrapper-wrapper.js:557
🎁CONFIG.Item.documentClass.updateDocuments#0 @ libWrapper-wrapper.js:144
update @ document.mjs:447
🎁call_wrapped @ libWrapper-wrapper.js:448
_update @ ItemContainer.js:150
🎁call_wrapper @ libWrapper-wrapper.js:557
🎁CONFIG.Item.documentClass.prototype.update#0 @ libWrapper-wrapper.js:144
importFromJSON @ foundry.js:9646
(anonymous) @ foundry.js:9671
Promise.then (async)
callback @ foundry.js:9671
submit @ foundry.js:20351
_onClickButton @ foundry.js:20314
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:9735 The Document#entity property has been deprecated in favor of Document#documentName. Support will be removed in 0.9.0

**Comment by ruipin** [comment] 2021-06-02 18:01
This does not seem to be caused by libWrapper, rather by some module using it.
Whatever module is wrapping `CONFIG.Item.documentClass.updateDocuments` is the likely culprit, try disabling this module and if the issue goes away, report it to them.

Closing as invalid.
Feel free to re-open if the issue still occurs after disabling all modules other than libWrapper.

**Closed by ruipin** 2021-06-02 18:01 UTC
