### ISSUE TITLE
SW5e: Libwrapper seems to be returning NaN for ability check mod, saving throw mod, AC, Initiative mod, and potentially others.

### ISSUE THREAD

**Issue by TogaParty** [ruipin/fvtt-lib-wrapper#65] opened 2022-03-28 16:19 UTC
⚠ Most errors triggered by libWrapper are not caused by libWrapper itself, but by a module/package. Do not open a support ticket using this form unless you are seeing an **internal** libWrapper error or are a **package developer** who needs support. We also do not provide support for packages that promote or otherwise endorse piracy. Your issue will be closed as invalid if you do not fulfill these requirements.

The easiest way to find support is to ask the community. The largest community-provided support channels are:
- [FoundryVTT Discord](https://discord.gg/foundryvtt)'s #modules-troubleshooting channel
- [FoundryVTT Reddit](https://www.reddit.com/r/FoundryVTT)

--------------------

**Confirm you have read the above**
Multiple issues reading underlying properties in the SW5e sheet.  The system hasn't been updated, this appears to be breaking multiple modules.

**Describe the bug**
Error when viewing the sheet, multiple values showing javascript null, "NaN", some showing blank.

When attempting to roll one of these abilities/checks, I get an error that may be helpful: 

**ability check/savingn throw:** 
entity.js:1260 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'hasProficiency')
[Detected 3 packages: system:sw5e, midi-qol, lib-wrapper]

**Attempting to edit AC:**
foundry.js:319 Error: Roll.safeEval produced a non-numeric result from expression "10 + @abilities.dex.mod"

Attempting to roll intiative:
combat.js:26 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'term')
[Detected 3 packages: system:sw5e, midi-qol, lib-wrapper]

**Technical Details (please complete the following information):**
Not browser dependent.
FVTT version is latest stable.
All modules updated and current.
I have a lot of modules installed, Find the Culprit reduces this problem to one of a number of modules, but all have dependencies on LibWrapper.

**Comment by ruipin** [comment] 2022-03-28 16:21
Please fill in all information requested in the bug report, such as the browser used, LibWrapper, FVTT and modules version, and how to reproduce.

**Comment by ruipin** [comment] 2022-03-28 16:28
Well, I can't reproduce on my end with the latest stable, sw5e, and midi-qol, which is why I asked.

Most likely not related to libWrapper, especially since it hasn't been updated in a few months. I suggest reporting these issues to the developers of the failing modules, most likely culprit from the messages would be midi-qol, which apparently was updated less than a week ago.

**Comment by ruipin** [comment] 2022-03-28 16:40
I believe the appropriate steps here would be to report the errors to the user of libWrapper (in this case, Midi-QOL). If they then debug it and find out it is indeed caused libWrapper, they will be much better positioned to open a bug report here (or update this report) with enough technical information for me to reproduce it and resolve the issue.

This is the reason for the text at the top of the bug report template:

> ⚠ Most errors triggered by libWrapper are not caused by libWrapper itself, but by a module/package. Do not open a support ticket using this form unless you are seeing an **internal** libWrapper error or are a **package developer** who needs support. We also do not provide support for packages that promote or otherwise endorse piracy. Your issue will be closed as invalid if you do not fulfill these requirements.

I'll leave this bug report open for a while, feel free to bring it to the attention of the Midi-QOL developers.

**Comment by TogaParty** [comment] 2022-03-28 18:39
It appears this is coming from DAE, which Midi-QOL also asks for.  I've opened a bug there.  Thanks for your help.

**Comment by ruipin** [comment] 2022-04-22 01:49
Closing, since it has been almost a month and I have gotten no further updates. Please reopen if it turns out the DAE team reveal this is caused by a libWrapper bug.

**Closed by ruipin** 2022-04-22 01:49 UTC
Labels: needs-information
